Repository snowplow-devops/conntest, pull requests merged in 2022-10, with the labels that each got.

#5 Document nix setup
  README.md
Labels: documentation

#7 Correct Snyk GitHub Action
  .github/workflows/snyk.yml
Labels: bug, fix

#6 Add copyright headers
  cmd/check_test.go
  cmd/root.go
  pkg/conntest.go
  pkg/conntest_integration_test.go
  pkg/conntest_test.go
  pkg/databricks.go
  pkg/databricks_test.go
  pkg/types.go
Labels: documentation, enhancement
